beds_min_choices = {
    'No Min': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
}

beds_max_choices = {
    'Studio': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    'No Max': 999,
}

price_min_choices = {
    'No Min': 0,
    '$400': 400,
    '$700': 700,
    '$1000': 1000,
    '$1300': 1300,
    '$1600': 1600,
}

price_max_choices = {
    '$1000': 1000,
    '$1300': 1300,
    '$1600': 1600,
    '$1900': 1900,
    '$2200': 2200,
    '$2500': 2500,
    'No Max': 99999,
}

type_choices = {
    'house': 'House',
    'apartment': 'Apaprtment',
    'condo': 'Condo',
    'townhouse': 'Townhouse',
    'other': 'Other'
}

states_choices = {
    'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AS': 'American Samoa',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'GU': 'Guam',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MP': 'Northern Mariana Islands',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'NA': 'National',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'PR': 'Puerto Rico',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'VI': 'Virgin Islands',
    'VT': 'Vermont',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'WY': 'Wyoming'
}
